[project]
name = "multi-agent-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "langgraph",
  "claude-agent-sdk",
  "grandalf>=0.8",
  "pydantic>=2.12.5",
]
